//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EbayOrdersDownloaderConsole
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OrderManagerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OrderManagerEntities object using the connection string found in the 'OrderManagerEntities' section of the application configuration file.
        /// </summary>
        public OrderManagerEntities() : base("name=OrderManagerEntities", "OrderManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OrderManagerEntities object.
        /// </summary>
        public OrderManagerEntities(string connectionString) : base(connectionString, "OrderManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OrderManagerEntities object.
        /// </summary>
        public OrderManagerEntities(EntityConnection connection) : base(connection, "OrderManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DetailRecord> DetailRecord
        {
            get
            {
                if ((_DetailRecord == null))
                {
                    _DetailRecord = base.CreateObjectSet<DetailRecord>("DetailRecord");
                }
                return _DetailRecord;
            }
        }
        private ObjectSet<DetailRecord> _DetailRecord;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HeaderRecords> HeaderRecords
        {
            get
            {
                if ((_HeaderRecords == null))
                {
                    _HeaderRecords = base.CreateObjectSet<HeaderRecords>("HeaderRecords");
                }
                return _HeaderRecords;
            }
        }
        private ObjectSet<HeaderRecords> _HeaderRecords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderMessage> OrderMessage
        {
            get
            {
                if ((_OrderMessage == null))
                {
                    _OrderMessage = base.CreateObjectSet<OrderMessage>("OrderMessage");
                }
                return _OrderMessage;
            }
        }
        private ObjectSet<OrderMessage> _OrderMessage;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OrderStatus> OrderStatus
        {
            get
            {
                if ((_OrderStatus == null))
                {
                    _OrderStatus = base.CreateObjectSet<OrderStatus>("OrderStatus");
                }
                return _OrderStatus;
            }
        }
        private ObjectSet<OrderStatus> _OrderStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DetailRecord EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDetailRecord(DetailRecord detailRecord)
        {
            base.AddObject("DetailRecord", detailRecord);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HeaderRecords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHeaderRecords(HeaderRecords headerRecords)
        {
            base.AddObject("HeaderRecords", headerRecords);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderMessage EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderMessage(OrderMessage orderMessage)
        {
            base.AddObject("OrderMessage", orderMessage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OrderStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrderStatus(OrderStatus orderStatus)
        {
            base.AddObject("OrderStatus", orderStatus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OrderManagerModel", Name="DetailRecord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DetailRecord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DetailRecord object.
        /// </summary>
        /// <param name="invoiceID">Initial value of the InvoiceID property.</param>
        /// <param name="purchaseID">Initial value of the PurchaseID property.</param>
        public static DetailRecord CreateDetailRecord(global::System.String invoiceID, global::System.String purchaseID)
        {
            DetailRecord detailRecord = new DetailRecord();
            detailRecord.InvoiceID = invoiceID;
            detailRecord.PurchaseID = purchaseID;
            return detailRecord;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InvoiceID
        {
            get
            {
                return _InvoiceID;
            }
            set
            {
                if (_InvoiceID != value)
                {
                    OnInvoiceIDChanging(value);
                    ReportPropertyChanging("InvoiceID");
                    _InvoiceID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("InvoiceID");
                    OnInvoiceIDChanged();
                }
            }
        }
        private global::System.String _InvoiceID;
        partial void OnInvoiceIDChanging(global::System.String value);
        partial void OnInvoiceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PurchaseID
        {
            get
            {
                return _PurchaseID;
            }
            set
            {
                if (_PurchaseID != value)
                {
                    OnPurchaseIDChanging(value);
                    ReportPropertyChanging("PurchaseID");
                    _PurchaseID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PurchaseID");
                    OnPurchaseIDChanged();
                }
            }
        }
        private global::System.String _PurchaseID;
        partial void OnPurchaseIDChanging(global::System.String value);
        partial void OnPurchaseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VolumeID
        {
            get
            {
                return _VolumeID;
            }
            set
            {
                OnVolumeIDChanging(value);
                ReportPropertyChanging("VolumeID");
                _VolumeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VolumeID");
                OnVolumeIDChanged();
            }
        }
        private global::System.String _VolumeID;
        partial void OnVolumeIDChanging(global::System.String value);
        partial void OnVolumeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VolumeName
        {
            get
            {
                return _VolumeName;
            }
            set
            {
                OnVolumeNameChanging(value);
                ReportPropertyChanging("VolumeName");
                _VolumeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VolumeName");
                OnVolumeNameChanged();
            }
        }
        private global::System.String _VolumeName;
        partial void OnVolumeNameChanging(global::System.String value);
        partial void OnVolumeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SourceCode
        {
            get
            {
                return _SourceCode;
            }
            set
            {
                OnSourceCodeChanging(value);
                ReportPropertyChanging("SourceCode");
                _SourceCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SourceCode");
                OnSourceCodeChanged();
            }
        }
        private global::System.String _SourceCode;
        partial void OnSourceCodeChanging(global::System.String value);
        partial void OnSourceCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductSKUCode
        {
            get
            {
                return _ProductSKUCode;
            }
            set
            {
                OnProductSKUCodeChanging(value);
                ReportPropertyChanging("ProductSKUCode");
                _ProductSKUCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductSKUCode");
                OnProductSKUCodeChanged();
            }
        }
        private global::System.String _ProductSKUCode;
        partial void OnProductSKUCodeChanging(global::System.String value);
        partial void OnProductSKUCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductDescription
        {
            get
            {
                return _ProductDescription;
            }
            set
            {
                OnProductDescriptionChanging(value);
                ReportPropertyChanging("ProductDescription");
                _ProductDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductDescription");
                OnProductDescriptionChanged();
            }
        }
        private global::System.String _ProductDescription;
        partial void OnProductDescriptionChanging(global::System.String value);
        partial void OnProductDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private Nullable<global::System.Decimal> _Quantity;
        partial void OnQuantityChanging(Nullable<global::System.Decimal> value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                OnUnitPriceChanging(value);
                ReportPropertyChanging("UnitPrice");
                _UnitPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitPrice");
                OnUnitPriceChanged();
            }
        }
        private Nullable<global::System.Double> _UnitPrice;
        partial void OnUnitPriceChanging(Nullable<global::System.Double> value);
        partial void OnUnitPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ExtendedPrice
        {
            get
            {
                return _ExtendedPrice;
            }
            set
            {
                OnExtendedPriceChanging(value);
                ReportPropertyChanging("ExtendedPrice");
                _ExtendedPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExtendedPrice");
                OnExtendedPriceChanged();
            }
        }
        private Nullable<global::System.Double> _ExtendedPrice;
        partial void OnExtendedPriceChanging(Nullable<global::System.Double> value);
        partial void OnExtendedPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CouponCodes
        {
            get
            {
                return _CouponCodes;
            }
            set
            {
                OnCouponCodesChanging(value);
                ReportPropertyChanging("CouponCodes");
                _CouponCodes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CouponCodes");
                OnCouponCodesChanged();
            }
        }
        private global::System.String _CouponCodes;
        partial void OnCouponCodesChanging(global::System.String value);
        partial void OnCouponCodesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> I_StatusCode
        {
            get
            {
                return _I_StatusCode;
            }
            set
            {
                OnI_StatusCodeChanging(value);
                ReportPropertyChanging("I_StatusCode");
                _I_StatusCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_StatusCode");
                OnI_StatusCodeChanged();
            }
        }
        private Nullable<global::System.Decimal> _I_StatusCode;
        partial void OnI_StatusCodeChanging(Nullable<global::System.Decimal> value);
        partial void OnI_StatusCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> I_ShipDate
        {
            get
            {
                return _I_ShipDate;
            }
            set
            {
                OnI_ShipDateChanging(value);
                ReportPropertyChanging("I_ShipDate");
                _I_ShipDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_ShipDate");
                OnI_ShipDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _I_ShipDate;
        partial void OnI_ShipDateChanging(Nullable<global::System.DateTime> value);
        partial void OnI_ShipDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String I_Tracking
        {
            get
            {
                return _I_Tracking;
            }
            set
            {
                OnI_TrackingChanging(value);
                ReportPropertyChanging("I_Tracking");
                _I_Tracking = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("I_Tracking");
                OnI_TrackingChanged();
            }
        }
        private global::System.String _I_Tracking;
        partial void OnI_TrackingChanging(global::System.String value);
        partial void OnI_TrackingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> I_ShippingMethod
        {
            get
            {
                return _I_ShippingMethod;
            }
            set
            {
                OnI_ShippingMethodChanging(value);
                ReportPropertyChanging("I_ShippingMethod");
                _I_ShippingMethod = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_ShippingMethod");
                OnI_ShippingMethodChanged();
            }
        }
        private Nullable<global::System.Decimal> _I_ShippingMethod;
        partial void OnI_ShippingMethodChanging(Nullable<global::System.Decimal> value);
        partial void OnI_ShippingMethodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> I_SyncWithShop
        {
            get
            {
                return _I_SyncWithShop;
            }
            set
            {
                OnI_SyncWithShopChanging(value);
                ReportPropertyChanging("I_SyncWithShop");
                _I_SyncWithShop = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_SyncWithShop");
                OnI_SyncWithShopChanged();
            }
        }
        private Nullable<global::System.Int32> _I_SyncWithShop;
        partial void OnI_SyncWithShopChanging(Nullable<global::System.Int32> value);
        partial void OnI_SyncWithShopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> I_OriginalCost
        {
            get
            {
                return _I_OriginalCost;
            }
            set
            {
                OnI_OriginalCostChanging(value);
                ReportPropertyChanging("I_OriginalCost");
                _I_OriginalCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_OriginalCost");
                OnI_OriginalCostChanged();
            }
        }
        private Nullable<global::System.Double> _I_OriginalCost;
        partial void OnI_OriginalCostChanging(Nullable<global::System.Double> value);
        partial void OnI_OriginalCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> I_OriginalQTY
        {
            get
            {
                return _I_OriginalQTY;
            }
            set
            {
                OnI_OriginalQTYChanging(value);
                ReportPropertyChanging("I_OriginalQTY");
                _I_OriginalQTY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("I_OriginalQTY");
                OnI_OriginalQTYChanged();
            }
        }
        private Nullable<global::System.Decimal> _I_OriginalQTY;
        partial void OnI_OriginalQTYChanging(Nullable<global::System.Decimal> value);
        partial void OnI_OriginalQTYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Commision
        {
            get
            {
                return _Commision;
            }
            set
            {
                OnCommisionChanging(value);
                ReportPropertyChanging("Commision");
                _Commision = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Commision");
                OnCommisionChanged();
            }
        }
        private Nullable<global::System.Decimal> _Commision;
        partial void OnCommisionChanging(Nullable<global::System.Decimal> value);
        partial void OnCommisionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OrderManagerModel", Name="HeaderRecords")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HeaderRecords : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HeaderRecords object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="invoiceID">Initial value of the InvoiceID property.</param>
        /// <param name="source">Initial value of the Source property.</param>
        public static HeaderRecords CreateHeaderRecords(global::System.String orderID, global::System.String invoiceID, global::System.String source)
        {
            HeaderRecords headerRecords = new HeaderRecords();
            headerRecords.OrderID = orderID;
            headerRecords.InvoiceID = invoiceID;
            headerRecords.Source = source;
            return headerRecords;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.String _OrderID;
        partial void OnOrderIDChanging(global::System.String value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InvoiceID
        {
            get
            {
                return _InvoiceID;
            }
            set
            {
                if (_InvoiceID != value)
                {
                    OnInvoiceIDChanging(value);
                    ReportPropertyChanging("InvoiceID");
                    _InvoiceID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("InvoiceID");
                    OnInvoiceIDChanged();
                }
            }
        }
        private global::System.String _InvoiceID;
        partial void OnInvoiceIDChanging(global::System.String value);
        partial void OnInvoiceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private global::System.String _OrderDate;
        partial void OnOrderDateChanging(global::System.String value);
        partial void OnOrderDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShopperID
        {
            get
            {
                return _ShopperID;
            }
            set
            {
                OnShopperIDChanging(value);
                ReportPropertyChanging("ShopperID");
                _ShopperID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShopperID");
                OnShopperIDChanged();
            }
        }
        private global::System.String _ShopperID;
        partial void OnShopperIDChanging(global::System.String value);
        partial void OnShopperIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BilltoFirstName
        {
            get
            {
                return _BilltoFirstName;
            }
            set
            {
                OnBilltoFirstNameChanging(value);
                ReportPropertyChanging("BilltoFirstName");
                _BilltoFirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BilltoFirstName");
                OnBilltoFirstNameChanged();
            }
        }
        private global::System.String _BilltoFirstName;
        partial void OnBilltoFirstNameChanging(global::System.String value);
        partial void OnBilltoFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BilltoLastName
        {
            get
            {
                return _BilltoLastName;
            }
            set
            {
                OnBilltoLastNameChanging(value);
                ReportPropertyChanging("BilltoLastName");
                _BilltoLastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BilltoLastName");
                OnBilltoLastNameChanged();
            }
        }
        private global::System.String _BilltoLastName;
        partial void OnBilltoLastNameChanging(global::System.String value);
        partial void OnBilltoLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BilltoCompanyName
        {
            get
            {
                return _BilltoCompanyName;
            }
            set
            {
                OnBilltoCompanyNameChanging(value);
                ReportPropertyChanging("BilltoCompanyName");
                _BilltoCompanyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BilltoCompanyName");
                OnBilltoCompanyNameChanged();
            }
        }
        private global::System.String _BilltoCompanyName;
        partial void OnBilltoCompanyNameChanging(global::System.String value);
        partial void OnBilltoCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BilltoStreetAddress
        {
            get
            {
                return _BilltoStreetAddress;
            }
            set
            {
                OnBilltoStreetAddressChanging(value);
                ReportPropertyChanging("BilltoStreetAddress");
                _BilltoStreetAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BilltoStreetAddress");
                OnBilltoStreetAddressChanged();
            }
        }
        private global::System.String _BilltoStreetAddress;
        partial void OnBilltoStreetAddressChanging(global::System.String value);
        partial void OnBilltoStreetAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BilltoOptionalAddress
        {
            get
            {
                return _BilltoOptionalAddress;
            }
            set
            {
                OnBilltoOptionalAddressChanging(value);
                ReportPropertyChanging("BilltoOptionalAddress");
                _BilltoOptionalAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BilltoOptionalAddress");
                OnBilltoOptionalAddressChanged();
            }
        }
        private global::System.String _BilltoOptionalAddress;
        partial void OnBilltoOptionalAddressChanging(global::System.String value);
        partial void OnBilltoOptionalAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BilltoCity
        {
            get
            {
                return _BilltoCity;
            }
            set
            {
                OnBilltoCityChanging(value);
                ReportPropertyChanging("BilltoCity");
                _BilltoCity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BilltoCity");
                OnBilltoCityChanged();
            }
        }
        private global::System.String _BilltoCity;
        partial void OnBilltoCityChanging(global::System.String value);
        partial void OnBilltoCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BilltoState
        {
            get
            {
                return _BilltoState;
            }
            set
            {
                OnBilltoStateChanging(value);
                ReportPropertyChanging("BilltoState");
                _BilltoState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BilltoState");
                OnBilltoStateChanged();
            }
        }
        private global::System.String _BilltoState;
        partial void OnBilltoStateChanging(global::System.String value);
        partial void OnBilltoStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BilltoZip
        {
            get
            {
                return _BilltoZip;
            }
            set
            {
                OnBilltoZipChanging(value);
                ReportPropertyChanging("BilltoZip");
                _BilltoZip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BilltoZip");
                OnBilltoZipChanged();
            }
        }
        private global::System.String _BilltoZip;
        partial void OnBilltoZipChanging(global::System.String value);
        partial void OnBilltoZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BilltoCountry
        {
            get
            {
                return _BilltoCountry;
            }
            set
            {
                OnBilltoCountryChanging(value);
                ReportPropertyChanging("BilltoCountry");
                _BilltoCountry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BilltoCountry");
                OnBilltoCountryChanged();
            }
        }
        private global::System.String _BilltoCountry;
        partial void OnBilltoCountryChanging(global::System.String value);
        partial void OnBilltoCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BilltoRegion
        {
            get
            {
                return _BilltoRegion;
            }
            set
            {
                OnBilltoRegionChanging(value);
                ReportPropertyChanging("BilltoRegion");
                _BilltoRegion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BilltoRegion");
                OnBilltoRegionChanged();
            }
        }
        private global::System.String _BilltoRegion;
        partial void OnBilltoRegionChanging(global::System.String value);
        partial void OnBilltoRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BilltoPhone
        {
            get
            {
                return _BilltoPhone;
            }
            set
            {
                OnBilltoPhoneChanging(value);
                ReportPropertyChanging("BilltoPhone");
                _BilltoPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BilltoPhone");
                OnBilltoPhoneChanged();
            }
        }
        private global::System.String _BilltoPhone;
        partial void OnBilltoPhoneChanging(global::System.String value);
        partial void OnBilltoPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeliveryMethod
        {
            get
            {
                return _DeliveryMethod;
            }
            set
            {
                OnDeliveryMethodChanging(value);
                ReportPropertyChanging("DeliveryMethod");
                _DeliveryMethod = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeliveryMethod");
                OnDeliveryMethodChanged();
            }
        }
        private global::System.String _DeliveryMethod;
        partial void OnDeliveryMethodChanging(global::System.String value);
        partial void OnDeliveryMethodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductSubtotal
        {
            get
            {
                return _ProductSubtotal;
            }
            set
            {
                OnProductSubtotalChanging(value);
                ReportPropertyChanging("ProductSubtotal");
                _ProductSubtotal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductSubtotal");
                OnProductSubtotalChanged();
            }
        }
        private global::System.String _ProductSubtotal;
        partial void OnProductSubtotalChanging(global::System.String value);
        partial void OnProductSubtotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShippingAndHandling
        {
            get
            {
                return _ShippingAndHandling;
            }
            set
            {
                OnShippingAndHandlingChanging(value);
                ReportPropertyChanging("ShippingAndHandling");
                _ShippingAndHandling = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShippingAndHandling");
                OnShippingAndHandlingChanged();
            }
        }
        private global::System.String _ShippingAndHandling;
        partial void OnShippingAndHandlingChanging(global::System.String value);
        partial void OnShippingAndHandlingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TaxMultiplier
        {
            get
            {
                return _TaxMultiplier;
            }
            set
            {
                OnTaxMultiplierChanging(value);
                ReportPropertyChanging("TaxMultiplier");
                _TaxMultiplier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TaxMultiplier");
                OnTaxMultiplierChanged();
            }
        }
        private global::System.String _TaxMultiplier;
        partial void OnTaxMultiplierChanging(global::System.String value);
        partial void OnTaxMultiplierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tax
        {
            get
            {
                return _Tax;
            }
            set
            {
                OnTaxChanging(value);
                ReportPropertyChanging("Tax");
                _Tax = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tax");
                OnTaxChanged();
            }
        }
        private global::System.String _Tax;
        partial void OnTaxChanging(global::System.String value);
        partial void OnTaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Discount
        {
            get
            {
                return _Discount;
            }
            set
            {
                OnDiscountChanging(value);
                ReportPropertyChanging("Discount");
                _Discount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Discount");
                OnDiscountChanged();
            }
        }
        private global::System.String _Discount;
        partial void OnDiscountChanging(global::System.String value);
        partial void OnDiscountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OverallTotal
        {
            get
            {
                return _OverallTotal;
            }
            set
            {
                OnOverallTotalChanging(value);
                ReportPropertyChanging("OverallTotal");
                _OverallTotal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OverallTotal");
                OnOverallTotalChanged();
            }
        }
        private global::System.String _OverallTotal;
        partial void OnOverallTotalChanging(global::System.String value);
        partial void OnOverallTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreditCardType
        {
            get
            {
                return _CreditCardType;
            }
            set
            {
                OnCreditCardTypeChanging(value);
                ReportPropertyChanging("CreditCardType");
                _CreditCardType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreditCardType");
                OnCreditCardTypeChanged();
            }
        }
        private global::System.String _CreditCardType;
        partial void OnCreditCardTypeChanging(global::System.String value);
        partial void OnCreditCardTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreditCardNumber
        {
            get
            {
                return _CreditCardNumber;
            }
            set
            {
                OnCreditCardNumberChanging(value);
                ReportPropertyChanging("CreditCardNumber");
                _CreditCardNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreditCardNumber");
                OnCreditCardNumberChanged();
            }
        }
        private global::System.String _CreditCardNumber;
        partial void OnCreditCardNumberChanging(global::System.String value);
        partial void OnCreditCardNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreditCardExpiration
        {
            get
            {
                return _CreditCardExpiration;
            }
            set
            {
                OnCreditCardExpirationChanging(value);
                ReportPropertyChanging("CreditCardExpiration");
                _CreditCardExpiration = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreditCardExpiration");
                OnCreditCardExpirationChanged();
            }
        }
        private global::System.String _CreditCardExpiration;
        partial void OnCreditCardExpirationChanging(global::System.String value);
        partial void OnCreditCardExpirationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreditCardSecurityNumberCCV
        {
            get
            {
                return _CreditCardSecurityNumberCCV;
            }
            set
            {
                OnCreditCardSecurityNumberCCVChanging(value);
                ReportPropertyChanging("CreditCardSecurityNumberCCV");
                _CreditCardSecurityNumberCCV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CreditCardSecurityNumberCCV");
                OnCreditCardSecurityNumberCCVChanged();
            }
        }
        private global::System.String _CreditCardSecurityNumberCCV;
        partial void OnCreditCardSecurityNumberCCVChanging(global::System.String value);
        partial void OnCreditCardSecurityNumberCCVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NameOnCreditCard
        {
            get
            {
                return _NameOnCreditCard;
            }
            set
            {
                OnNameOnCreditCardChanging(value);
                ReportPropertyChanging("NameOnCreditCard");
                _NameOnCreditCard = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NameOnCreditCard");
                OnNameOnCreditCardChanged();
            }
        }
        private global::System.String _NameOnCreditCard;
        partial void OnNameOnCreditCardChanging(global::System.String value);
        partial void OnNameOnCreditCardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShiptoFirstName
        {
            get
            {
                return _ShiptoFirstName;
            }
            set
            {
                OnShiptoFirstNameChanging(value);
                ReportPropertyChanging("ShiptoFirstName");
                _ShiptoFirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShiptoFirstName");
                OnShiptoFirstNameChanged();
            }
        }
        private global::System.String _ShiptoFirstName;
        partial void OnShiptoFirstNameChanging(global::System.String value);
        partial void OnShiptoFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShiptoLastName
        {
            get
            {
                return _ShiptoLastName;
            }
            set
            {
                OnShiptoLastNameChanging(value);
                ReportPropertyChanging("ShiptoLastName");
                _ShiptoLastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShiptoLastName");
                OnShiptoLastNameChanged();
            }
        }
        private global::System.String _ShiptoLastName;
        partial void OnShiptoLastNameChanging(global::System.String value);
        partial void OnShiptoLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShiptoCompanyName
        {
            get
            {
                return _ShiptoCompanyName;
            }
            set
            {
                OnShiptoCompanyNameChanging(value);
                ReportPropertyChanging("ShiptoCompanyName");
                _ShiptoCompanyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShiptoCompanyName");
                OnShiptoCompanyNameChanged();
            }
        }
        private global::System.String _ShiptoCompanyName;
        partial void OnShiptoCompanyNameChanging(global::System.String value);
        partial void OnShiptoCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShiptoStreetAddress
        {
            get
            {
                return _ShiptoStreetAddress;
            }
            set
            {
                OnShiptoStreetAddressChanging(value);
                ReportPropertyChanging("ShiptoStreetAddress");
                _ShiptoStreetAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShiptoStreetAddress");
                OnShiptoStreetAddressChanged();
            }
        }
        private global::System.String _ShiptoStreetAddress;
        partial void OnShiptoStreetAddressChanging(global::System.String value);
        partial void OnShiptoStreetAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShiptoOptionalAddress
        {
            get
            {
                return _ShiptoOptionalAddress;
            }
            set
            {
                OnShiptoOptionalAddressChanging(value);
                ReportPropertyChanging("ShiptoOptionalAddress");
                _ShiptoOptionalAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShiptoOptionalAddress");
                OnShiptoOptionalAddressChanged();
            }
        }
        private global::System.String _ShiptoOptionalAddress;
        partial void OnShiptoOptionalAddressChanging(global::System.String value);
        partial void OnShiptoOptionalAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShiptoCity
        {
            get
            {
                return _ShiptoCity;
            }
            set
            {
                OnShiptoCityChanging(value);
                ReportPropertyChanging("ShiptoCity");
                _ShiptoCity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShiptoCity");
                OnShiptoCityChanged();
            }
        }
        private global::System.String _ShiptoCity;
        partial void OnShiptoCityChanging(global::System.String value);
        partial void OnShiptoCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShiptoState
        {
            get
            {
                return _ShiptoState;
            }
            set
            {
                OnShiptoStateChanging(value);
                ReportPropertyChanging("ShiptoState");
                _ShiptoState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShiptoState");
                OnShiptoStateChanged();
            }
        }
        private global::System.String _ShiptoState;
        partial void OnShiptoStateChanging(global::System.String value);
        partial void OnShiptoStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShiptoZip
        {
            get
            {
                return _ShiptoZip;
            }
            set
            {
                OnShiptoZipChanging(value);
                ReportPropertyChanging("ShiptoZip");
                _ShiptoZip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShiptoZip");
                OnShiptoZipChanged();
            }
        }
        private global::System.String _ShiptoZip;
        partial void OnShiptoZipChanging(global::System.String value);
        partial void OnShiptoZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShiptoCountry
        {
            get
            {
                return _ShiptoCountry;
            }
            set
            {
                OnShiptoCountryChanging(value);
                ReportPropertyChanging("ShiptoCountry");
                _ShiptoCountry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShiptoCountry");
                OnShiptoCountryChanged();
            }
        }
        private global::System.String _ShiptoCountry;
        partial void OnShiptoCountryChanging(global::System.String value);
        partial void OnShiptoCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShiptoRegion
        {
            get
            {
                return _ShiptoRegion;
            }
            set
            {
                OnShiptoRegionChanging(value);
                ReportPropertyChanging("ShiptoRegion");
                _ShiptoRegion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShiptoRegion");
                OnShiptoRegionChanged();
            }
        }
        private global::System.String _ShiptoRegion;
        partial void OnShiptoRegionChanging(global::System.String value);
        partial void OnShiptoRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShiptoPhone
        {
            get
            {
                return _ShiptoPhone;
            }
            set
            {
                OnShiptoPhoneChanging(value);
                ReportPropertyChanging("ShiptoPhone");
                _ShiptoPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShiptoPhone");
                OnShiptoPhoneChanged();
            }
        }
        private global::System.String _ShiptoPhone;
        partial void OnShiptoPhoneChanging(global::System.String value);
        partial void OnShiptoPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SHOPCOMCatalogID
        {
            get
            {
                return _SHOPCOMCatalogID;
            }
            set
            {
                OnSHOPCOMCatalogIDChanging(value);
                ReportPropertyChanging("SHOPCOMCatalogID");
                _SHOPCOMCatalogID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SHOPCOMCatalogID");
                OnSHOPCOMCatalogIDChanged();
            }
        }
        private global::System.String _SHOPCOMCatalogID;
        partial void OnSHOPCOMCatalogIDChanging(global::System.String value);
        partial void OnSHOPCOMCatalogIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CatalogName
        {
            get
            {
                return _CatalogName;
            }
            set
            {
                OnCatalogNameChanging(value);
                ReportPropertyChanging("CatalogName");
                _CatalogName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CatalogName");
                OnCatalogNameChanged();
            }
        }
        private global::System.String _CatalogName;
        partial void OnCatalogNameChanging(global::System.String value);
        partial void OnCatalogNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MultiplePaymentsQuantity
        {
            get
            {
                return _MultiplePaymentsQuantity;
            }
            set
            {
                OnMultiplePaymentsQuantityChanging(value);
                ReportPropertyChanging("MultiplePaymentsQuantity");
                _MultiplePaymentsQuantity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MultiplePaymentsQuantity");
                OnMultiplePaymentsQuantityChanged();
            }
        }
        private global::System.String _MultiplePaymentsQuantity;
        partial void OnMultiplePaymentsQuantityChanging(global::System.String value);
        partial void OnMultiplePaymentsQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CanSellNamePrivacyFlag
        {
            get
            {
                return _CanSellNamePrivacyFlag;
            }
            set
            {
                OnCanSellNamePrivacyFlagChanging(value);
                ReportPropertyChanging("CanSellNamePrivacyFlag");
                _CanSellNamePrivacyFlag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CanSellNamePrivacyFlag");
                OnCanSellNamePrivacyFlagChanged();
            }
        }
        private global::System.String _CanSellNamePrivacyFlag;
        partial void OnCanSellNamePrivacyFlagChanging(global::System.String value);
        partial void OnCanSellNamePrivacyFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CanSendOffersPrivacyFlag
        {
            get
            {
                return _CanSendOffersPrivacyFlag;
            }
            set
            {
                OnCanSendOffersPrivacyFlagChanging(value);
                ReportPropertyChanging("CanSendOffersPrivacyFlag");
                _CanSendOffersPrivacyFlag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CanSendOffersPrivacyFlag");
                OnCanSendOffersPrivacyFlagChanged();
            }
        }
        private global::System.String _CanSendOffersPrivacyFlag;
        partial void OnCanSendOffersPrivacyFlagChanging(global::System.String value);
        partial void OnCanSendOffersPrivacyFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShopperComments
        {
            get
            {
                return _ShopperComments;
            }
            set
            {
                OnShopperCommentsChanging(value);
                ReportPropertyChanging("ShopperComments");
                _ShopperComments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShopperComments");
                OnShopperCommentsChanged();
            }
        }
        private global::System.String _ShopperComments;
        partial void OnShopperCommentsChanging(global::System.String value);
        partial void OnShopperCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PayPalTxnID
        {
            get
            {
                return _PayPalTxnID;
            }
            set
            {
                OnPayPalTxnIDChanging(value);
                ReportPropertyChanging("PayPalTxnID");
                _PayPalTxnID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PayPalTxnID");
                OnPayPalTxnIDChanged();
            }
        }
        private global::System.String _PayPalTxnID;
        partial void OnPayPalTxnIDChanging(global::System.String value);
        partial void OnPayPalTxnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GiftMessage
        {
            get
            {
                return _GiftMessage;
            }
            set
            {
                OnGiftMessageChanging(value);
                ReportPropertyChanging("GiftMessage");
                _GiftMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GiftMessage");
                OnGiftMessageChanged();
            }
        }
        private global::System.String _GiftMessage;
        partial void OnGiftMessageChanging(global::System.String value);
        partial void OnGiftMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Commision
        {
            get
            {
                return _Commision;
            }
            set
            {
                OnCommisionChanging(value);
                ReportPropertyChanging("Commision");
                _Commision = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Commision");
                OnCommisionChanged();
            }
        }
        private global::System.String _Commision;
        partial void OnCommisionChanging(global::System.String value);
        partial void OnCommisionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OrderManagerModel", Name="OrderMessage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderMessage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderMessage object.
        /// </summary>
        /// <param name="invoiceID">Initial value of the InvoiceID property.</param>
        public static OrderMessage CreateOrderMessage(global::System.String invoiceID)
        {
            OrderMessage orderMessage = new OrderMessage();
            orderMessage.InvoiceID = invoiceID;
            return orderMessage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InvoiceID
        {
            get
            {
                return _InvoiceID;
            }
            set
            {
                if (_InvoiceID != value)
                {
                    OnInvoiceIDChanging(value);
                    ReportPropertyChanging("InvoiceID");
                    _InvoiceID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("InvoiceID");
                    OnInvoiceIDChanged();
                }
            }
        }
        private global::System.String _InvoiceID;
        partial void OnInvoiceIDChanging(global::System.String value);
        partial void OnInvoiceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String To
        {
            get
            {
                return _To;
            }
            set
            {
                OnToChanging(value);
                ReportPropertyChanging("To");
                _To = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("To");
                OnToChanged();
            }
        }
        private global::System.String _To;
        partial void OnToChanging(global::System.String value);
        partial void OnToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String From
        {
            get
            {
                return _From;
            }
            set
            {
                OnFromChanging(value);
                ReportPropertyChanging("From");
                _From = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("From");
                OnFromChanged();
            }
        }
        private global::System.String _From;
        partial void OnFromChanging(global::System.String value);
        partial void OnFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeliveryDate
        {
            get
            {
                return _DeliveryDate;
            }
            set
            {
                OnDeliveryDateChanging(value);
                ReportPropertyChanging("DeliveryDate");
                _DeliveryDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeliveryDate");
                OnDeliveryDateChanged();
            }
        }
        private global::System.String _DeliveryDate;
        partial void OnDeliveryDateChanging(global::System.String value);
        partial void OnDeliveryDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OrderManagerModel", Name="OrderStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OrderStatus object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        public static OrderStatus CreateOrderStatus(global::System.String orderID)
        {
            OrderStatus orderStatus = new OrderStatus();
            orderStatus.OrderID = orderID;
            return orderStatus;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.String _OrderID;
        partial void OnOrderIDChanging(global::System.String value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tracking
        {
            get
            {
                return _Tracking;
            }
            set
            {
                OnTrackingChanging(value);
                ReportPropertyChanging("Tracking");
                _Tracking = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tracking");
                OnTrackingChanged();
            }
        }
        private global::System.String _Tracking;
        partial void OnTrackingChanging(global::System.String value);
        partial void OnTrackingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ShipMethod
        {
            get
            {
                return _ShipMethod;
            }
            set
            {
                OnShipMethodChanging(value);
                ReportPropertyChanging("ShipMethod");
                _ShipMethod = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShipMethod");
                OnShipMethodChanged();
            }
        }
        private Nullable<global::System.Int32> _ShipMethod;
        partial void OnShipMethodChanging(Nullable<global::System.Int32> value);
        partial void OnShipMethodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShipDate
        {
            get
            {
                return _ShipDate;
            }
            set
            {
                OnShipDateChanging(value);
                ReportPropertyChanging("ShipDate");
                _ShipDate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShipDate");
                OnShipDateChanged();
            }
        }
        private global::System.String _ShipDate;
        partial void OnShipDateChanging(global::System.String value);
        partial void OnShipDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Synced
        {
            get
            {
                return _Synced;
            }
            set
            {
                OnSyncedChanging(value);
                ReportPropertyChanging("Synced");
                _Synced = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Synced");
                OnSyncedChanged();
            }
        }
        private Nullable<global::System.Int32> _Synced;
        partial void OnSyncedChanging(Nullable<global::System.Int32> value);
        partial void OnSyncedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProcessedBy
        {
            get
            {
                return _ProcessedBy;
            }
            set
            {
                OnProcessedByChanging(value);
                ReportPropertyChanging("ProcessedBy");
                _ProcessedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProcessedBy");
                OnProcessedByChanged();
            }
        }
        private Nullable<global::System.Int32> _ProcessedBy;
        partial void OnProcessedByChanging(Nullable<global::System.Int32> value);
        partial void OnProcessedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PONum
        {
            get
            {
                return _PONum;
            }
            set
            {
                OnPONumChanging(value);
                ReportPropertyChanging("PONum");
                _PONum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PONum");
                OnPONumChanged();
            }
        }
        private global::System.String _PONum;
        partial void OnPONumChanging(global::System.String value);
        partial void OnPONumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Vendor
        {
            get
            {
                return _Vendor;
            }
            set
            {
                OnVendorChanging(value);
                ReportPropertyChanging("Vendor");
                _Vendor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vendor");
                OnVendorChanged();
            }
        }
        private Nullable<global::System.Int32> _Vendor;
        partial void OnVendorChanging(Nullable<global::System.Int32> value);
        partial void OnVendorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InvoiceNum
        {
            get
            {
                return _InvoiceNum;
            }
            set
            {
                OnInvoiceNumChanging(value);
                ReportPropertyChanging("InvoiceNum");
                _InvoiceNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InvoiceNum");
                OnInvoiceNumChanged();
            }
        }
        private global::System.String _InvoiceNum;
        partial void OnInvoiceNumChanging(global::System.String value);
        partial void OnInvoiceNumChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OrderManagerModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    
}
